name: Publish Website

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy website
        run: npm run build
