name: Publish Website

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: clean cache
        run: npm cache clean --force
      - name: install
        run: npm ci
      - name: npm install
        run: npm install
      - name: deploy
        run: npm run predeploy && npm run deploy
